Tools: optimsoc-app-link creates now directories
optimsoc-app-link now creates a directory structure in the target equal
to the one present in the source directory. Only files are symlinked,
the directory structure is recreated.

diff --git a/tools/utils/optimsoc-app-link b/tools/utils/optimsoc-app-link
--- a/tools/utils/optimsoc-app-link
+++ b/tools/utils/optimsoc-app-link
@@ -1,6 +1,7 @@
 #!/bin/bash
+set -e
 
-# sw_copy <system> <application>
+# optimsoc-app-link <system> <application>
 
 if [ $# -lt 2 ]; then
    echo "Usage: optimsoc-app-link <system> <application>"
@@ -10,22 +11,28 @@ if [ $# -lt 2 ]; then
    exit
 fi
 
-folder=${2/\//_}.lnk
+targetdir=$PWD/${2/\//_}.lnk
+srcdir=${OPTIMSOC}/src/sw/system/apps/$1/$2
 
-if [ -d $folder ]; then
-    echo "directory $bname already exists"
-    exit
+if [ ! -d $srcdir ]; then
+    echo "Cannot find sources directory $srcdir."
+    exit 1
 fi
 
-mkdir $folder
-
-if [ ! -d ${OPTIMSOC}/src/sw/system/apps/$1/$2 ]; then
-    echo "Cannot find ${OPTIMSOC}/src/sw/system/apps/$1/$2"
-    rmdir $folder
-    exit
+if [ -d $targetdir ]; then
+    echo "Target directory $targetdir already exists."
+    exit 1
 fi
 
-for f in `find ${OPTIMSOC}/src/sw/system/apps/$1/$2 -type f`; do
-    bf=`echo $f | sed 's|'${OPTIMSOC}/src/sw/system/apps/$1/$2/'||'`
-    ln -s $f $folder/$bf
+mkdir $targetdir
+
+wd=$PWD
+cd $srcdir
+
+for f in `find . -type f`; do
+    dirname=`dirname $f`
+    [ -d $targetdir/$dirname ] || mkdir $targetdir/$dirname
+    ln -s $srcdir/$f $targetdir/$f
 done
+
+cd $wd
